layout_spectrum: 0.3319391746430815
typography_spectrum: 0.18871252139919611
color:
  brandStrength: 0.7281578098781554
  lightness: 0.6314221726658542
  saturation: 0.8301261501531532
  rhythmicContrast: 0.9561850467475481
  brandColors:
    - '#F4F2ED'
    - '#FBF9F1'
    - '#FDFDF9'
    - '#F0ECE8'
    - '#FFFFFF'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: ' '
content: []
title: ''
description: ''
purpose:
  - type: external
    url: 'https://thegrid.ai/storemkr'
    label: The Store
  - type: external
    url: 'https://thegrid.ai/modernkimono'
    label: Home
url: 'https://thegrid.ai/blogmkr/'
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1248868f-c4e0-4a2e-aec0-a5dabaf25dcf.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1a56d747-400f-4eb7-a367-ad1f82d49a9e.png
